### ISSUE TITLE
Server should give more specific errors

### ISSUE THREAD

**Issue by Netdex** [ecnivo/Flow#68]
FILE_NOT_FOUND? nope, INTERNAL_SERVER_ERROR!

**Comment by ecnivo** [comment]
LOL

**Comment by Bimde** [comment]
Any specific requests where this is applicable? As requests only return INTERNAL_SERVER_ERROR for errors that the client should not care about. I.e. FILE_NOT_FOUND should never be a message because if INVALID_FILE_UUID is not thrown, then there clearly is a server error (i.e. the database and filesystem are out of sync), which the client will NOT care about.

**Comment by Netdex** [comment]
The client may be out of sync (tree is not refreshed), and request a file that has been deleted by another user, where in this case INVALID_FILE_UUID would be a valid message to have returned.

**Comment by Bimde** [comment]
This is exactly what happens though:
![image](https://cloud.githubusercontent.com/assets/10459097/12374719/d6bf696c-bc72-11e5-821c-75e107151d52.png)

**Comment by Netdex** [comment]
I mean that there are other messages where this is not done.

**Comment by Bimde** [comment]
Re-open this issue if you find any examples of this, as I wasn't able to do so.
